version: "3"
networks:
  penpot:
    external: false
services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    depends_on:
      - penpot-backend
      - penpot-exporter
    env_file:
      - config.env
    networks:
      - penpot
    volumes:
      - penpot_assets_data:/opt/data
  penpot-backend:
    image: "penpotapp/backend:latest"
    depends_on:
      - penpot-postgres
      - penpot-redis
    env_file:
      - config.env
    networks:
      - penpot
    volumes:
      - penpot_assets_data:/opt/data
  penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot
  penpot-postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
    networks:
      - penpot
    stop_signal: SIGINT
    volumes:
      - penpot_postgres_data:/var/lib/postgresql/data
  penpot-redis:
    image: redis:6
    networks:
      - penpot
volumes:
  penpot_postgres_data:
  penpot_assets_data:
