version: "3"
services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    depends_on:
      - penpot-backend
      - penpot-exporter
    env_file:
      - config.env
    volumes:
      - penpot_assets:/opt/data/assets
  penpot-backend:
    image: "penpotapp/backend:latest"
    depends_on:
      - penpot-postgres
      - penpot-redis
    env_file:
      - config.env
    volumes:
      - penpot_assets:/opt/data/assets
  penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0
  penpot-postgres:
    image: "postgres:15"
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
    stop_signal: SIGINT
    volumes:
      - penpot_postgres:/var/lib/postgresql/data
  penpot-redis:
    image: redis:7
volumes:
  penpot_postgres:
  penpot_assets:
